using Cadence.Application.Common.Abstractions;
using Cadence.Domain.Enums;
using Cadence.Domain.Intelligence.Events;
using Cadence.Domain.Work;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Cadence.Application.Modules.ActionItems;

/// <summary>
/// Turns the commitments the model flagged into real tasks — when, and only when, the organizer has
/// said they may be created without a human looking at them first.
/// </summary>
/// <remarks>
/// <para>
/// <b>The gate is the point of this handler.</b> Extraction is a model guessing who promised what
/// from a transcript, and it is wrong often enough that writing straight into a colleague's task
/// list is not an acceptable default. Two preferences have to agree before anything is written:
/// <c>AutoExtractActionItems</c> must be on, and <c>RequireActionItemReview</c> must be off. Both
/// default to on, so out of the box <b>nothing is created automatically</b>.
/// </para>
/// <para>
/// <b>Known gap.</b> When review is required the candidates are logged and dropped — there is no
/// durable "pending review" store, and the client has no screen that would read one. The interactive
/// review path today is the live meeting page, where a user accepts detected items as they appear.
/// An inbox for the asynchronous path belongs with notifications (task 17); half-building it here
/// would mean a queue nothing ever drains.
/// </para>
/// <para>
/// Creation is <b>idempotent by title within a meeting</b>. Hangfire delivers at least once and a
/// user can regenerate a summary by hand, so this handler will run more than once for some meeting.
/// Without the check, every rerun would file the same commitments again.
/// </para>
/// </remarks>
public sealed class CreateDetectedActionItems(
    ICadenceDbContext context,
    ILogger<CreateDetectedActionItems> logger)
    : IDomainEventHandler<ActionItemsDetected>
{
    public async Task HandleAsync(
        ActionItemsDetected domainEvent,
        CancellationToken cancellationToken = default)
    {
        if (domainEvent.Items.Count == 0)
        {
            return;
        }

        var meeting = await context.Meetings
            .AsNoTracking()
            .Where(candidate => candidate.Id == domainEvent.MeetingId)
            .Select(candidate => new { candidate.Id, candidate.OrganizerId })
            .FirstOrDefaultAsync(cancellationToken);

        if (meeting is null)
        {
            return;
        }

        // The organizer's settings, not the caller's: a summary regenerated by a teammate must not
        // apply that teammate's tolerance for auto-created work to somebody else's meeting.
        var preferences = await context.UserPreferences
            .AsNoTracking()
            .Where(row => row.UserId == meeting.OrganizerId)
            .Select(row => new { row.Ai.AutoExtractActionItems, row.Ai.RequireActionItemReview })
            .FirstOrDefaultAsync(cancellationToken);

        // No preferences row means the safe reading, not the permissive one.
        var autoExtract = preferences?.AutoExtractActionItems ?? true;
        var requireReview = preferences?.RequireActionItemReview ?? true;

        if (!autoExtract)
        {
            return;
        }

        if (requireReview)
        {
            logger.LogInformation(
                "Held {Count} detected action items for meeting {MeetingId}: the organizer requires review",
                domainEvent.Items.Count,
                domainEvent.MeetingId);

            return;
        }

        // Soft-deleted rows count as existing. A task the user deleted after the last run was a
        // decision about that commitment; a regeneration must not quietly undo it. The tenant is
        // named explicitly because IgnoreQueryFilters drops the tenant filter along with the
        // soft-delete one.
        var existingTitles = await context.ActionItems
            .AsNoTracking()
            .IgnoreQueryFilters()
            .Where(item => item.OrganizationId == domainEvent.OrganizationId
                && item.MeetingId == domainEvent.MeetingId)
            .Select(item => item.Title)
            .ToListAsync(cancellationToken);

        var seen = new HashSet<string>(existingTitles, StringComparer.OrdinalIgnoreCase);
        var created = 0;

        foreach (var detected in domainEvent.Items)
        {
            if (string.IsNullOrWhiteSpace(detected.Title) || !seen.Add(detected.Title.Trim()))
            {
                continue;
            }

            var item = ActionItem.FromMeeting(
                domainEvent.OrganizationId,
                // Filed by the organizer rather than by whoever triggered the run, so the task's
                // creator is stable across a regeneration.
                meeting.OrganizerId,
                domainEvent.MeetingId,
                detected.SourceSegmentId,
                detected.Title.Trim(),
                detected.AssigneeId,
                ActionItemPriority.Medium);

            await context.ActionItems.AddAsync(item, cancellationToken);
            created++;
        }

        if (created == 0)
        {
            return;
        }

        await context.SaveChangesAsync(cancellationToken);

        logger.LogInformation(
            "Created {Count} action items detected in meeting {MeetingId}",
            created,
            domainEvent.MeetingId);
    }
}
