"use client";

import {
  AlertTriangle,
  CircleHelp,
  Gavel,
  RefreshCw,
  Sparkles,
  Star,
} from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { EmptyState, Skeleton } from "@/components/ui/feedback";
import { useToast } from "@/components/ui/toast";
import { generateSummary } from "@/lib/api/meetings";
import { formatRelative, formatTimecode } from "@/lib/utils/format";
import type { AISummary, Meeting, SummaryHighlightKind } from "@/types/domain";

const HIGHLIGHT_GROUPS: {
  kind: SummaryHighlightKind;
  title: string;
  description: string;
  icon: typeof Gavel;
  accent: string;
}[] = [
  {
    kind: "decision",
    title: "Decisions",
    description: "What the group committed to.",
    icon: Gavel,
    accent: "text-success-foreground",
  },
  {
    kind: "risk",
    title: "Risks",
    description: "What could go wrong, and why it matters.",
    icon: AlertTriangle,
    accent: "text-danger-foreground",
  },
  {
    kind: "question",
    title: "Open questions",
    description: "Left unresolved in this meeting.",
    icon: CircleHelp,
    accent: "text-warning-foreground",
  },
  {
    kind: "highlight",
    title: "Highlights",
    description: "Moments worth revisiting.",
    icon: Star,
    accent: "text-accent",
  },
];

export function SummaryPanel({
  meeting,
  summary,
  loading,
  hasTranscript,
  onRegenerated,
}: {
  meeting: Meeting;
  summary: AISummary | null;
  loading: boolean;
  hasTranscript: boolean;
  onRegenerated: () => void;
}) {
  const [generating, setGenerating] = useState(false);
  const { toast } = useToast();

  async function handleGenerate() {
    setGenerating(true);
    try {
      await generateSummary(meeting.id);
      onRegenerated();
      toast({
        tone: "success",
        title: summary ? "Summary regenerated" : "Summary generated",
      });
    } catch (error) {
      toast({
        tone: "error",
        title: "Could not generate summary",
        description:
          error instanceof Error ? error.message : "Please try again.",
      });
    } finally {
      setGenerating(false);
    }
  }

  if (loading) {
    return (
      <div className="space-y-4 p-4">
        <Skeleton className="h-4 w-40" />
        <Skeleton className="h-20 w-full" />
        <Skeleton className="h-4 w-32" />
        <Skeleton className="h-32 w-full" />
      </div>
    );
  }

  if (!summary) {
    return (
      <EmptyState
        icon={Sparkles}
        title="No summary yet"
        description={
          hasTranscript
            ? "Generate an AI summary from this meeting's transcript."
            : "A transcript is required before a summary can be generated."
        }
        action={
          hasTranscript ? (
            <Button
              variant="primary"
              size="sm"
              loading={generating}
              onClick={handleGenerate}
            >
              <Sparkles />
              Generate summary
            </Button>
          ) : undefined
        }
      />
    );
  }

  return (
    <div className="space-y-6 p-4">
      {/* Provenance — never present model output as if a person wrote it. */}
      <div className="flex flex-wrap items-center justify-between gap-2 rounded-control border border-border bg-surface-sunken px-3 py-2">
        <p className="flex items-center gap-1.5 text-caption text-muted">
          <Sparkles className="size-3.5 text-accent" aria-hidden />
          Generated by{" "}
          <span className="font-medium text-foreground">{summary.model}</span>
          <span aria-hidden>·</span>
          {formatRelative(summary.generatedAt)}
        </p>

        <Button
          variant="ghost"
          size="sm"
          loading={generating}
          onClick={handleGenerate}
        >
          <RefreshCw />
          Regenerate
        </Button>
      </div>

      {/* Executive summary */}
      <section className="space-y-2">
        <h3 className="text-overline uppercase text-subtle">
          Executive summary
        </h3>
        <p className="max-w-3xl text-body leading-6 text-foreground">
          {summary.executiveSummary}
        </p>
      </section>

      {/* Key points */}
      {summary.keyPoints.length > 0 ? (
        <section className="space-y-2">
          <h3 className="text-overline uppercase text-subtle">
            Key discussion points
          </h3>
          <ul className="max-w-3xl space-y-2">
            {summary.keyPoints.map((point) => (
              <li key={point} className="flex gap-2.5">
                <span
                  aria-hidden
                  className="mt-2 size-1 shrink-0 rounded-full bg-border-strong"
                />
                <span className="text-body text-muted">{point}</span>
              </li>
            ))}
          </ul>
        </section>
      ) : null}

      {/* Grouped highlights */}
      <div className="grid gap-4 lg:grid-cols-2">
        {HIGHLIGHT_GROUPS.map((group) => {
          const entries = summary.highlights.filter(
            (highlight) => highlight.kind === group.kind,
          );
          if (entries.length === 0) return null;

          return (
            <section
              key={group.kind}
              className="rounded-surface border border-border"
            >
              <header className="border-b border-border px-3 py-2">
                <h3 className="flex items-center gap-1.5 text-caption font-semibold text-foreground">
                  <group.icon
                    className={`size-3.5 ${group.accent}`}
                    aria-hidden
                  />
                  {group.title}
                  <span className="text-subtle tabular">
                    ({entries.length})
                  </span>
                </h3>
                <p className="mt-0.5 text-label text-subtle">
                  {group.description}
                </p>
              </header>

              <ul className="divide-y divide-border">
                {entries.map((entry) => (
                  <li key={entry.id} className="px-3 py-2.5">
                    <p className="text-body text-muted">{entry.text}</p>
                    {entry.atSeconds !== null ? (
                      <p className="mt-1 font-mono text-label text-subtle tabular">
                        {formatTimecode(entry.atSeconds)}
                      </p>
                    ) : null}
                  </li>
                ))}
              </ul>
            </section>
          );
        })}
      </div>
    </div>
  );
}
