// <auto-generated />
using System;
using System.Collections.Generic;
using Cadence.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cadence.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CadenceDbContext))]
    [Migration("20260720115545_MembershipStatus")]
    partial class MembershipStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cadence.Domain.Chat.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_chat_message");

                    b.HasIndex("ConversationId", "CreatedAt")
                        .HasDatabaseName("ix_chat_message_conversation_id_created_at");

                    b.ToTable("chat_message", null, t =>
                        {
                            t.HasCheckConstraint("ck_chat_message_role", "role IN ('user', 'assistant')");
                        });
                });

            modelBuilder.Entity("Cadence.Domain.Chat.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTimeOffset>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<Guid?>("MeetingId")
                        .HasColumnType("uuid")
                        .HasColumnName("meeting_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_conversation");

                    b.HasIndex("MeetingId")
                        .HasDatabaseName("ix_conversation_meeting_id");

                    b.HasIndex("UserId", "LastMessageAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_conversation_user_id_last_message_at")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("conversation", (string)null);
                });

            modelBuilder.Entity("Cadence.Domain.Collaboration.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("Href")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("href");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("summary");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.HasKey("Id")
                        .HasName("pk_activity_log");

                    b.HasIndex("OrganizationId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_activity_log_organization_id_occurred_at");

                    b.ToTable("activity_log", null, t =>
                        {
                            t.HasCheckConstraint("ck_activity_log_kind", "kind IN ('meeting_created', 'meeting_completed', 'summary_generated', 'task_created', 'task_completed', 'document_uploaded', 'member_joined', 'comment_added')");
                        });
                });

            modelBuilder.Entity("Cadence.Domain.Collaboration.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AtSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("at_seconds");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid")
                        .HasColumnName("meeting_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.PrimitiveCollection<List<Guid>>("_mentions")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("mentions");

                    b.HasKey("Id")
                        .HasName("pk_comment");

                    b.HasIndex("MeetingId")
                        .HasDatabaseName("ix_comment_meeting_id")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_comment_parent_id");

                    b.ToTable("comment", (string)null);
                });

            modelBuilder.Entity("Cadence.Domain.Collaboration.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Href")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("href");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notification");

                    b.HasIndex("UserId", "IsRead", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_notification_user_id_is_read_created_at");

                    b.ToTable("notification", null, t =>
                        {
                            t.HasCheckConstraint("ck_notification_kind", "kind IN ('transcript_ready', 'summary_ready', 'meeting_reminder', 'task_assigned', 'mention', 'document_uploaded')");
                        });
                });

            modelBuilder.Entity("Cadence.Domain.Identity.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key_hash");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("prefix");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.PrimitiveCollection<string[]>("_scopes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("scopes");

                    b.HasKey("Id")
                        .HasName("pk_api_key");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_api_key_key_hash");

                    b.ToTable("api_key", (string)null);
                });

            modelBuilder.Entity("Cadence.Domain.Identity.ExternalLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EmailAtProvider")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email_at_provider");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_external_login");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_external_login_user_id");

                    b.HasIndex("Provider", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ix_external_login_provider_subject");

                    b.ToTable("external_login", (string)null);
                });

            modelBuilder.Entity("Cadence.Domain.Identity.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedById")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_invitation");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_invitation_token_hash");

                    b.HasIndex("OrganizationId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_invitation_organization_id_email")
                        .HasFilter("status = 'pending'");

                    b.ToTable("invitation", null, t =>
                        {
                            t.HasCheckConstraint("ck_invitation_role", "role IN ('owner', 'admin', 'member', 'guest')");

                            t.HasCheckConstraint("ck_invitation_status", "status IN ('pending', 'accepted', 'revoked', 'expired')");
                        });
                });

            modelBuilder.Entity("Cadence.Domain.Identity.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_organization");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_organization_slug")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("organization", null, t =>
                        {
                            t.HasCheckConstraint("ck_organization_plan", "plan IN ('free', 'team', 'business', 'enterprise')");
                        });
                });

            modelBuilder.Entity("Cadence.Domain.Identity.OrganizationMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_organization_member");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_organization_member_user_id");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_organization_member_organization_id_user_id");

                    b.ToTable("organization_member", null, t =>
                        {
                            t.HasCheckConstraint("ck_organization_member_role", "role IN ('owner', 'admin', 'member', 'guest')");

                            t.HasCheckConstraint("ck_organization_member_status", "status IN ('active', 'invited', 'suspended')");
                        });
                });

            modelBuilder.Entity("Cadence.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Device")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("device");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_token_family_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_refresh_token_organization_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_token_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_token_user_id");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("Cadence.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("job_title");

                    b.Property<DateTimeOffset>("LastActiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("user", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_status", "status IN ('active', 'invited', 'suspended')");
                        });
                });

            modelBuilder.Entity("Cadence.Domain.Identity.UserPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CalendarView")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("calendar_view");

                    b.Property<string>("Density")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("density");

                    b.Property<string>("KnowledgeView")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("knowledge_view");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("MeetingsView")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meetings_view");

                    b.Property<bool>("SidebarCollapsed")
                        .HasColumnType("boolean")
                        .HasColumnName("sidebar_collapsed");

                    b.Property<string>("TasksView")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tasks_view");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("theme");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.PrimitiveCollection<List<Guid>>("_recentMeetingIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("recent_meeting_ids");

                    b.PrimitiveCollection<List<string>>("_recentSearches")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("recent_searches");

                    b.HasKey("Id")
                        .HasName("pk_user_preferences");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_preferences_user_id");

                    b.ToTable("user_preferences", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_preferences_calendar_view", "calendar_view IN ('month', 'week', 'day')");

                            t.HasCheckConstraint("ck_user_preferences_density", "density IN ('comfortable', 'compact')");

                            t.HasCheckConstraint("ck_user_preferences_knowledge_view", "knowledge_view IN ('list', 'grid')");

                            t.HasCheckConstraint("ck_user_preferences_meetings_view", "meetings_view IN ('list', 'grid')");

                            t.HasCheckConstraint("ck_user_preferences_tasks_view", "tasks_view IN ('list', 'board', 'calendar')");

                            t.HasCheckConstraint("ck_user_preferences_theme", "theme IN ('light', 'dark', 'system')");
                        });
                });

            modelBuilder.Entity("Cadence.Domain.Integrations.Integration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountLabel")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("account_label");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset?>("ConnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connected_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_integration");

                    b.HasIndex("OrganizationId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_integration_organization_id_key");

                    b.ToTable("integration", null, t =>
                        {
                            t.HasCheckConstraint("ck_integration_category", "category IN ('meetings', 'calendar', 'storage', 'productivity')");

                            t.HasCheckConstraint("ck_integration_status", "status IN ('connected', 'disconnected', 'error')");
                        });
                });

            modelBuilder.Entity("Cadence.Domain.Intelligence.AiSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("ExecutiveSummary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("executive_summary");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid")
                        .HasColumnName("meeting_id");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.PrimitiveCollection<string>("_keyPoints")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("key_points");

                    b.HasKey("Id")
                        .HasName("pk_ai_summary");

                    b.HasIndex("MeetingId")
                        .IsUnique()
                        .HasDatabaseName("ix_ai_summary_meeting_id");

                    b.ToTable("ai_summary", (string)null);
                });

            modelBuilder.Entity("Cadence.Domain.Intelligence.SummaryHighlight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AtSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("at_seconds");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<Guid?>("SourceSegmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_segment_id");

                    b.Property<Guid>("SummaryId")
                        .HasColumnType("uuid")
                        .HasColumnName("summary_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_summary_highlight");

                    b.HasIndex("SourceSegmentId")
                        .HasDatabaseName("ix_summary_highlight_source_segment_id");

                    b.HasIndex("SummaryId", "Kind")
                        .HasDatabaseName("ix_summary_highlight_summary_id_kind");

                    b.ToTable("summary_highlight", null, t =>
                        {
                            t.HasCheckConstraint("ck_summary_highlight_kind", "kind IN ('decision', 'risk', 'question', 'highlight')");
                        });
                });

            modelBuilder.Entity("Cadence.Domain.Library.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("excerpt");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_favorite");

                    b.Property<Guid?>("MeetingId")
                        .HasColumnType("uuid")
                        .HasColumnName("meeting_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("processing_status");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.PrimitiveCollection<List<string>>("_tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.HasKey("Id")
                        .HasName("pk_document");

                    b.HasIndex("MeetingId")
                        .HasDatabaseName("ix_document_meeting_id");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ix_document_storage_key");

                    b.HasIndex("OrganizationId", "ProcessingStatus")
                        .HasDatabaseName("ix_document_organization_id_processing_status")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("document", null, t =>
                        {
                            t.HasCheckConstraint("ck_document_processing_status", "processing_status IN ('uploading', 'processing', 'indexed', 'failed')");

                            t.HasCheckConstraint("ck_document_size_non_negative", "size_bytes >= 0");

                            t.HasCheckConstraint("ck_document_type", "type IN ('pdf', 'docx', 'pptx', 'txt', 'csv', 'image')");
                        });
                });

            modelBuilder.Entity("Cadence.Domain.Library.KnowledgeItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("excerpt");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_favorite");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LastOpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_opened_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.PrimitiveCollection<List<string>>("_tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_item");

                    b.HasIndex("_tags")
                        .HasDatabaseName("ix_knowledge_item_tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("_tags"), "gin");

                    b.HasIndex("OrganizationId", "Category")
                        .HasDatabaseName("ix_knowledge_item_organization_id_category")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("knowledge_item", null, t =>
                        {
                            t.HasCheckConstraint("ck_knowledge_item_kind", "kind IN ('document', 'meeting_note', 'ai_summary', 'link')");
                        });
                });

            modelBuilder.Entity("Cadence.Domain.Meetings.Bookmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AtSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("at_seconds");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("label");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid")
                        .HasColumnName("meeting_id");

                    b.HasKey("Id")
                        .HasName("pk_bookmark");

                    b.HasIndex("MeetingId")
                        .HasDatabaseName("ix_bookmark_meeting_id");

                    b.ToTable("bookmark", null, t =>
                        {
                            t.HasCheckConstraint("ck_bookmark_position_non_negative", "at_seconds >= 0");
                        });
                });

            modelBuilder.Entity("Cadence.Domain.Meetings.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_favorite");

                    b.Property<string>("MeetingUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("meeting_url");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizer_id");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("RecordingStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recording_status");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SummaryStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary_status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.PrimitiveCollection<List<string>>("_tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.HasKey("Id")
                        .HasName("pk_meeting");

                    b.HasIndex("_tags")
                        .HasDatabaseName("ix_meeting_tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("_tags"), "gin");

                    b.HasIndex("OrganizationId", "StartsAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_meeting_organization_id_starts_at")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_meeting_organization_id_status")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("meeting", null, t =>
                        {
                            t.HasCheckConstraint("ck_meeting_duration_non_negative", "duration_seconds >= 0");

                            t.HasCheckConstraint("ck_meeting_ends_after_starts", "ends_at > starts_at");

                            t.HasCheckConstraint("ck_meeting_platform", "platform IN ('zoom', 'google_meet', 'teams', 'in_person')");

                            t.HasCheckConstraint("ck_meeting_recording_status", "recording_status IN ('not_recorded', 'recording', 'paused', 'recorded', 'failed')");

                            t.HasCheckConstraint("ck_meeting_status", "status IN ('scheduled', 'live', 'processing', 'completed', 'cancelled')");

                            t.HasCheckConstraint("ck_meeting_summary_status", "summary_status IN ('none', 'queued', 'generating', 'ready', 'failed')");
                        });
                });

            modelBuilder.Entity("Cadence.Domain.Meetings.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Attended")
                        .HasColumnType("boolean")
                        .HasColumnName("attended");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid")
                        .HasColumnName("meeting_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<double>("TalkTimeRatio")
                        .HasColumnType("double precision")
                        .HasColumnName("talk_time_ratio");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_participant");

                    b.HasIndex("MeetingId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_participant_meeting_id_user_id");

                    b.ToTable("participant", null, t =>
                        {
                            t.HasCheckConstraint("ck_participant_role", "role IN ('host', 'presenter', 'attendee')");

                            t.HasCheckConstraint("ck_participant_talk_time_ratio", "talk_time_ratio >= 0 AND talk_time_ratio <= 1");
                        });
                });

            modelBuilder.Entity("Cadence.Domain.Meetings.TranscriptSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int>("EndMs")
                        .HasColumnType("integer")
                        .HasColumnName("end_ms");

                    b.Property<bool>("IsActionItem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_action_item");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid")
                        .HasColumnName("meeting_id");

                    b.Property<Guid?>("SpeakerId")
                        .HasColumnType("uuid")
                        .HasColumnName("speaker_id");

                    b.Property<string>("SpeakerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("speaker_name");

                    b.Property<int>("StartMs")
                        .HasColumnType("integer")
                        .HasColumnName("start_ms");

                    b.HasKey("Id")
                        .HasName("pk_transcript_segment");

                    b.HasIndex("SpeakerId")
                        .HasDatabaseName("ix_transcript_segment_speaker_id");

                    b.HasIndex("MeetingId", "StartMs")
                        .HasDatabaseName("ix_transcript_segment_meeting_id_start_ms");

                    b.ToTable("transcript_segment", null, t =>
                        {
                            t.HasCheckConstraint("ck_transcript_segment_confidence", "confidence BETWEEN 0 AND 1");

                            t.HasCheckConstraint("ck_transcript_segment_range", "end_ms >= start_ms");
                        });
                });

            modelBuilder.Entity("Cadence.Domain.Work.ActionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<Guid?>("MeetingId")
                        .HasColumnType("uuid")
                        .HasColumnName("meeting_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<Guid?>("SourceSegmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_segment_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.PrimitiveCollection<List<string>>("_tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.HasKey("Id")
                        .HasName("pk_action_item");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("ix_action_item_assignee_id");

                    b.HasIndex("MeetingId")
                        .HasDatabaseName("ix_action_item_meeting_id");

                    b.HasIndex("SourceSegmentId")
                        .HasDatabaseName("ix_action_item_source_segment_id");

                    b.HasIndex("OrganizationId", "DueDate")
                        .HasDatabaseName("ix_action_item_organization_id_due_date")
                        .HasFilter("status <> 'done' AND deleted_at IS NULL");

                    b.HasIndex("OrganizationId", "AssigneeId", "Status")
                        .HasDatabaseName("ix_action_item_organization_id_assignee_id_status")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("action_item", null, t =>
                        {
                            t.HasCheckConstraint("ck_action_item_priority", "priority IN ('low', 'medium', 'high', 'urgent')");

                            t.HasCheckConstraint("ck_action_item_status", "status IN ('todo', 'in_progress', 'blocked', 'done')");
                        });
                });

            modelBuilder.Entity("Cadence.Domain.Chat.ChatMessage", b =>
                {
                    b.HasOne("Cadence.Domain.Chat.Conversation", null)
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_message_conversation_conversation_id");

                    b.OwnsMany("Cadence.Domain.Chat.ChatSource", "Sources", b1 =>
                        {
                            b1.Property<Guid>("ChatMessageId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Href")
                                .IsRequired()
                                .HasMaxLength(2048);

                            b1.Property<string>("Kind")
                                .IsRequired();

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(500);

                            b1.Property<Guid>("SourceId");

                            b1.HasKey("ChatMessageId", "__synthesizedOrdinal")
                                .HasName("pk_chat_messages");

                            b1.ToTable("chat_message");

                            b1
                                .ToJson("sources")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ChatMessageId")
                                .HasConstraintName("fk_chat_message_chat_message_chatmessageid");
                        });

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("Cadence.Domain.Chat.Conversation", b =>
                {
                    b.HasOne("Cadence.Domain.Meetings.Meeting", null)
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_conversation_meeting_meeting_id");
                });

            modelBuilder.Entity("Cadence.Domain.Collaboration.Comment", b =>
                {
                    b.HasOne("Cadence.Domain.Meetings.Meeting", null)
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_meeting_meeting_id");

                    b.HasOne("Cadence.Domain.Collaboration.Comment", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_comment_comment_parent_id");
                });

            modelBuilder.Entity("Cadence.Domain.Collaboration.Notification", b =>
                {
                    b.HasOne("Cadence.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_user_user_id");
                });

            modelBuilder.Entity("Cadence.Domain.Identity.ExternalLogin", b =>
                {
                    b.HasOne("Cadence.Domain.Identity.User", null)
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_login_user_user_id");
                });

            modelBuilder.Entity("Cadence.Domain.Identity.Organization", b =>
                {
                    b.OwnsOne("Cadence.Domain.Identity.WorkspaceSettings", "Settings", b1 =>
                        {
                            b1.Property<Guid>("OrganizationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("DefaultVisibility")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("settings_default_visibility");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("settings_name");

                            b1.Property<string>("Retention")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("settings_retention");

                            b1.HasKey("OrganizationId");

                            b1.ToTable("organization", t =>
                                {
                                    t.HasCheckConstraint("ck_organization_settings_default_visibility", "settings_default_visibility IN ('workspace', 'participants', 'private')");

                                    t.HasCheckConstraint("ck_organization_settings_retention", "settings_retention IN ('three_months', 'twelve_months', 'forever')");
                                });

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId")
                                .HasConstraintName("fk_organization_organization_id");
                        });

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("Cadence.Domain.Identity.OrganizationMember", b =>
                {
                    b.HasOne("Cadence.Domain.Identity.Organization", null)
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_member_organization_organization_id");

                    b.HasOne("Cadence.Domain.Identity.User", null)
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_member_user_user_id");
                });

            modelBuilder.Entity("Cadence.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("Cadence.Domain.Identity.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_organization_organization_id");

                    b.HasOne("Cadence.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_user_user_id");
                });

            modelBuilder.Entity("Cadence.Domain.Identity.UserPreferences", b =>
                {
                    b.HasOne("Cadence.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_preferences_user_user_id");

                    b.OwnsOne("Cadence.Domain.Identity.AiPreferences", "Ai", b1 =>
                        {
                            b1.Property<Guid>("UserPreferencesId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<bool>("AutoExtractActionItems")
                                .HasColumnType("boolean")
                                .HasColumnName("ai_auto_extract_action_items");

                            b1.Property<bool>("AutoSummarise")
                                .HasColumnType("boolean")
                                .HasColumnName("ai_auto_summarise");

                            b1.Property<string>("OutputLanguage")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("ai_output_language");

                            b1.Property<bool>("RequireActionItemReview")
                                .HasColumnType("boolean")
                                .HasColumnName("ai_require_action_item_review");

                            b1.Property<string>("SummaryLength")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("ai_summary_length");

                            b1.HasKey("UserPreferencesId");

                            b1.ToTable("user_preferences", t =>
                                {
                                    t.HasCheckConstraint("ck_user_preferences_ai_summary_length", "ai_summary_length IN ('brief', 'standard', 'detailed')");
                                });

                            b1.WithOwner()
                                .HasForeignKey("UserPreferencesId")
                                .HasConstraintName("fk_user_preferences_user_preferences_id");
                        });

                    b.OwnsOne("Cadence.Domain.Identity.NotificationPreferences", "Notifications", b1 =>
                        {
                            b1.Property<Guid>("UserPreferencesId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.PrimitiveCollection<string[]>("Email")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("notifications_email");

                            b1.PrimitiveCollection<string[]>("InApp")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("notifications_in_app");

                            b1.HasKey("UserPreferencesId");

                            b1.ToTable("user_preferences");

                            b1.WithOwner()
                                .HasForeignKey("UserPreferencesId")
                                .HasConstraintName("fk_user_preferences_user_preferences_id");
                        });

                    b.Navigation("Ai")
                        .IsRequired();

                    b.Navigation("Notifications")
                        .IsRequired();
                });

            modelBuilder.Entity("Cadence.Domain.Intelligence.AiSummary", b =>
                {
                    b.HasOne("Cadence.Domain.Meetings.Meeting", null)
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_summary_meeting_meeting_id");
                });

            modelBuilder.Entity("Cadence.Domain.Intelligence.SummaryHighlight", b =>
                {
                    b.HasOne("Cadence.Domain.Meetings.TranscriptSegment", null)
                        .WithMany()
                        .HasForeignKey("SourceSegmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_summary_highlight_transcript_segment_source_segment_id");

                    b.HasOne("Cadence.Domain.Intelligence.AiSummary", null)
                        .WithMany("Highlights")
                        .HasForeignKey("SummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_summary_highlight_ai_summary_summary_id");
                });

            modelBuilder.Entity("Cadence.Domain.Library.Document", b =>
                {
                    b.HasOne("Cadence.Domain.Meetings.Meeting", null)
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_document_meeting_meeting_id");
                });

            modelBuilder.Entity("Cadence.Domain.Meetings.Bookmark", b =>
                {
                    b.HasOne("Cadence.Domain.Meetings.Meeting", null)
                        .WithMany("Bookmarks")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookmark_meeting_meeting_id");
                });

            modelBuilder.Entity("Cadence.Domain.Meetings.Participant", b =>
                {
                    b.HasOne("Cadence.Domain.Meetings.Meeting", null)
                        .WithMany("Participants")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_participant_meeting_meeting_id");
                });

            modelBuilder.Entity("Cadence.Domain.Meetings.TranscriptSegment", b =>
                {
                    b.HasOne("Cadence.Domain.Meetings.Meeting", null)
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transcript_segment_meeting_meeting_id");

                    b.HasOne("Cadence.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("SpeakerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_transcript_segment_user_speaker_id");
                });

            modelBuilder.Entity("Cadence.Domain.Work.ActionItem", b =>
                {
                    b.HasOne("Cadence.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_action_item_user_assignee_id");

                    b.HasOne("Cadence.Domain.Meetings.Meeting", null)
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_action_item_meeting_meeting_id");

                    b.HasOne("Cadence.Domain.Meetings.TranscriptSegment", null)
                        .WithMany()
                        .HasForeignKey("SourceSegmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_action_item_transcript_segment_source_segment_id");
                });

            modelBuilder.Entity("Cadence.Domain.Chat.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Cadence.Domain.Identity.Organization", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Cadence.Domain.Identity.User", b =>
                {
                    b.Navigation("ExternalLogins");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Cadence.Domain.Intelligence.AiSummary", b =>
                {
                    b.Navigation("Highlights");
                });

            modelBuilder.Entity("Cadence.Domain.Meetings.Meeting", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
